title: My Personal Website
description: A personal website built with Jekyll
url: http://example.com
author:
  name: Your Name
  email: your.email@example.com
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - _includes
  - _layouts
  - _posts
  - assets