title: My Personal Website
description: A personal website built with Jekyll
url: https://guysio.github.io/myweb
author:
  name: guysio
  email: guyluxury6@gmail.com
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - _includes
  - _layouts
  - _posts
  - assets